const data =[
    {
    id:1,
    brandProductId:7,
    categoryId:2,
    isDiscontinued:false,
  isNew:false,
  internal:false,
    productShortDescription:"TV Hisense 43 Smart Digital Satellite Television",
    brandsName:"Hisense",
    pgName:"Tv",
    productDescription:"TV Hisense 43 Smart Digital Satellite Television",
    productSpecifications:"TV Hisense 43 Smart Digital Satellite Television",
    unitListPrice:100,
    productGroupId:1,
    productAttributes:"TV Hisense 43 Smart Digital Satellite Television",
    productImage:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/product_images/Hisense/211/Images_515x512_curve.png",
    productAssetss:[{
        source:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/product_images/Hisense/204/Product_600x600_58.png",
        is_Default:true
    },
    {
        source:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/product_images/Hisense/212/Images_515x512_80.jpg",
        is_Default:true
    }
],
    
    productsSubCategories:"tvs",
    defaultDiscountPrice:90,
   
    },


    {
        id:2,
        categoryId:3,
        brandProductId:6,
        isDiscontinued:false,
  isNew:true,
  internal:false,
        productShortDescription:"TV Hisense 43 Smart Digital Satellite Television",
        brandsName:"Hisense",
        pgName:"Tv",
        productDescription:"TV Hisense 43 Smart Digital Satellite Television",
        productSpecifications:"TV Hisense 43 Smart Digital Satellite Television",
        unitListPrice:100,
        productGroupId:1,
        productAttributes:"TV Hisense 43 Smart Digital Satellite Television",
        productImage:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/product_images/Hisense/204/Product_600x600_58.png",
        productsSubCategories:"",
        defaultDiscountPrice:90,

        },
        {
            id:3,
           categoryId:4,
           brandProductId:5,
           isDiscontinued:false,
  isNew:false,
  internal:true,
            productShortDescription:"TV Hisense 43 Smart Digital Satellite Television",
            brandsName:"Hisense",
            pgName:"Tv",
            productIndexName:"ts",
            productDescription:"TV Hisense 43 Smart Digital Satellite Television",
            productSpecifications:"TV Hisense 43 Smart Digital Satellite Television",
            unitListPrice:100,
            productGroupId:1,
            productAttributes:"TV Hisense 43 Smart Digital Satellite Television",
            productImage:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/company_images/1/homepage/Images_515x512_ac_on%26off1_1603253920835_1609906235444.png",
            productsSubCategories:"",
            defaultDiscountPrice:90,
           
            },
            {
                id:4,
                categoryId:2,
                brandProductId:4,
                isDiscontinued:true,
                isNew:false,
                internal:false,
                productShortDescription:"TV Hisense 43 Smart Digital Satellite Television",
                brandsName:"Hisense",
                pgName:"Tv",
                productDescription:"TV Hisense 43 Smart Digital Satellite Television",
                productSpecifications:"TV Hisense 43 Smart Digital Satellite Television",
                unitListPrice:100,
                productGroupId:1,
                productAttributes:"TV Hisense 43 Smart Digital Satellite Television",
                productImage:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/product_images/Hisense/204/Product_600x600_58.png",
                productsSubCategories:"",
                defaultDiscountPrice:90,
               
                productIndexName:"ts",
               
                },
                {
                    id:5,
                   categoryId:2,
                   isDiscontinued:false,
                         isNew:false,
                     internal:false,
                    productShortDescription:"TV Hisense 43 Smart Digital Satellite Television",
                    brandsName:"Hisense",
                    brandProductId:2,
                    pgName:"Tv",
                    productIndexName:"ts",
                    productDescription:"TV Hisense 43 Smart Digital Satellite Television",
                    productSpecifications:"TV Hisense 43 Smart Digital Satellite Television",
                    unitListPrice:100,
                    productGroupId:1,
                    productAttributes:"TV Hisense 43 Smart Digital Satellite Television",
                    productImage:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/company_images/1/homepage/Images_515x512_525_1603253916573_1609906232435.png",
                    productsSubCategories:"",
                    defaultDiscountPrice:90,
                   
                    },
                    {
                        id:6,
                       categoryId:1,
                       brandProductId:3,
                       isDiscontinued:false,
                        isNew:false,
                        internal:false,
                        productShortDescription:"TV Hisense 43 Smart Digital Satellite Television",
                        brandsName:"Hisense",
                        pgName:"Tv",
                        productDescription:"TV Hisense 43 Smart Digital Satellite Television",
                        productSpecifications:"TV Hisense 43 Smart Digital Satellite Television",
                        unitListPrice:90,
                        productGroupId:1,
                        productAttributes:"TV Hisense 43 Smart Digital Satellite Television",
                        productImage:"https://hisense2-myapptino-assets.s3.eu-west-2.amazonaws.com/app_assets/product_images/Hisense/204/Product_600x600_58.png",
                        productsSubCategories:"",
                        defaultDiscountPrice:90,
                        
                        }
]
export default data